window.INVITATION_DATA = {
  couple: {
    firstName: "Anderson",
    secondName: "Aleena",
    displayName: "Anderson & Aleena",
  },
  text: {
    pageTitle: "Anderson & Aleena | Wedding Invitation",
    shareDescription:
      "Join Anderson and Aleena for their wedding celebration on Saturday, 11 July 2026.",
    coverKicker: "Wedding Invitation",
    coverButton: "Tap to Open",
    navStory: "Story",
    navMoments: "Moments",
    navDetails: "Details",
    coupleKicker: "With joyful hearts",
    heroKicker: "Together with their families",
    heroHeading: "You are invited to their wedding celebration.",
    storyKicker: "The invitation",
    storyHeading: "From quiet walks to forever vows.",
    storyBody:
      "It started with a digital matrimonial connection, but it became real at L'eto. What was supposed to be a simple first meeting turned into hours of endless talking, laughing, and truly getting to know one another. As days turned into beautiful moments together, the realization was simple and clear, as our hearts arrived at the exact same question: Why not a forever?",
    eventTitle: "Ceremony & Reception",
    detailsKicker: "Wedding day",
    whenLabel: "When",
    whereLabel: "Where",
    lunchLabel: "Lunch thereafter",
    dressLabel: "Dress code",
    dressCode: "Modest and formal attire",
    dressNote: "Graceful celebration wear",
    heroRsvpButton: "RSVP",
    musicButton: "Music",
    mapButton: "Open Map",
    countdownDays: "Days",
    countdownHours: "Hours",
    countdownMinutes: "Minutes",
    countdownSeconds: "Seconds",
    blessingKicker: "A blessing",
    blessingVerse:
      '"Above all these things, walk in love, which is the bond of perfection."',
    blessingReference: "Colossians 3:14",
    rsvpKicker: "Kindly reply",
    rsvpHeading: "Celebrate with Anderson & Aleena.",
    rsvpButton: "Send RSVP",
  },
  event: {
    displayDate: "Saturday, 11 July 2026",
    displayTime: "11:00 AM onwards",
    countdownDateTime: "2026-07-11T11:00:00+04:00",
    venueName: "St. Sebastian Roman Catholic Latin Church",
    venueAddress: "Aluvassery",
    lunchVenueName: "Thevarcad Convention Center",
    lunchVenueAddress: "Valliyode, Vadakkenchery",
  },
  schedule: [],
  links: {
    map: "https://share.google/w8WOPwwkm27WQ8IJU",
    lunchMap: "https://share.google/5dU8iUFFAut6sTn9U",
    rsvp: "mailto:hello@example.com",
  },
  assets: {
    music: "assets/music.mp3",
    sharePreview: "assets/share-preview.jpg",
    coverPhoto: "assets/photo-2-mobile.webp",
    coupleBackground: "assets/photo-5-mobile.webp",
    heroPhoto: "assets/couple-hero-mobile.webp",
    qrCode: "assets/map-qr.svg",
    lunchQrCode: "assets/lunch-map-qr.svg",
    gallery: [
      {
        src: "assets/photo-1-mobile.webp",
        alt: "Anderson and Aleena walking together in the woods",
      },
      {
        src: "assets/photo-2-mobile.webp",
        alt: "Close portrait of Anderson and Aleena smiling",
      },
      {
        src: "assets/photo-3-mobile.webp",
        alt: "Anderson and Aleena holding hands by the sea",
      },
      {
        src: "assets/photo-4-mobile.webp",
        alt: "Anderson and Aleena smiling on the beach",
      },
      {
        src: "assets/photo-5-mobile.webp",
        alt: "Anderson and Aleena facing the ocean",
      },
      {
        src: "assets/couple-hero-mobile.webp",
        alt: "Anderson and Aleena dancing in the woods",
      },
    ],
  },
};
